FROM ubuntu:25.10

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    git \
    gdb \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src